### ISSUE TITLE
Kernel and app crash reports (kDump and coredump)

### ISSUE THREAD

**Issue by t-lo** [kinvolk/Flatcar#446]
Currently, Flatcar's failure reports are rather limited (syslog etc.). Supporting reports generated by kDump (for kernel crashes) and journal / `coredumpctl` (for system-level application crashes, like e.g. Docker, containerd, etc.) will increase visibility of system-level failure modes.

Items:
- [ ] Integrate kDump to generate and to store kernel crash reports
- [ ] Integrate coredumpctl to generate and to store application crash reports
  - [ ] Use default list of applications which can be extended / modified via parameters
- [ ] Act on crash reports present on a system and engage Mayday
- [ ] Extend Mayday to support sending crash reports
