### ISSUE TITLE
Release Flatcar Container Linux Alpha 3535.0.0, Beta 3510.1.0, Stable 3374.2.5, LTS-2022 3033.3.10

### ISSUE THREAD

**Issue by sayanchowdhury** [kinvolk/Flatcar#971]
## Release Flatcar Container Linux Alpha 3535.0.0, Beta 3510.1.0, Stable 3374.2.5, LTS-2022 3033.3.10
  
The release of Flatcar Container Linux  the following channels is planned for March 6th, 2023.
- Alpha 3535.0.0 (major release)
- Beta 3510.1.0 (major release)
- Stable 3374.2.5 (maintenance release) 
- LTS-2022 3033.3.10 (maintenance release)

### Tasks
- [x] Go / No Go [hackmd doc](https://hackmd.io/iVdMjg3qRqSihEaGTM6NiQ) created from previous one for test tracking and release notes: [link](https://hackmd.io/iVdMjg3qRqSihEaGTM6NiQ) (@sayanchowdhury)
- [x] Check that the kernel PR are merged for the channel(s) to be released. (@sayanchowdhury)
- [x] All planned changes are merged & blocker bugs are fixed, last nightly reviewed for problems (@sayanchowdhury)
- [x] Branch off main (only new major) (@sayanchowdhury)
- [x] Tag build branch (@sayanchowdhury)
- [x] Start Jenkins builds, post links as comment (@sayanchowdhury)
- [x] Test status captured in hackmd doc (@sayanchowdhury)
- [x] All tests are green (@sayanchowdhury)
- [x] Release notes / announcements added to Go/No Go doc from `container/image_changes` job by selecting `Timestamps: None` (@sayanchowdhury)
- [x] QA: check diff for image file list, packages, and image size in the image job output (@sayanchowdhury)
- [x] Matrix Go/No Go meeting (inc. release notes review) (@sayanchowdhury)
- [x] Update payload signed/uploaded (@tormath1)
- [x] `scripts` release created on GitHub (@sayanchowdhury)
- [x] Release job `container/release` ran (@sayanchowdhury)
- [x] Images uploaded with `copy-to-origin.sh` (@sayanchowdhury)
- [x] Azure offer updated & publishing started (@sayanchowdhury)
- [x] Azure Go Live (@sayanchowdhury)
- [x] GCP offers updated (@sayanchowdhury)
- [x] For new Stable: Manually run `./azure-sig.sh` to create new Shared Community Gallery Images
- [x] For new Stable: build and provide images for supported Cluster API providers (@tormath1)
- [x] Symlink to "current" updated with `set-symlink.sh` (@sayanchowdhury)
- [x] Website updated with `./update-flatcar-versions.sh` and PR merged (@sayanchowdhury)
- [x] Release package published in Nebraska (@tormath1)
- [x] Send announcement to Mailing Lists (@miao0miao, @tormath1) (public list in done)
- [x] Send Tweet out (@miao0miao, @ahrkrak)
- [x] Brief version announcement in slack (k8s slack #flatcar) and the Flatcar matrix channel (@tormath1)

**Comment by sayanchowdhury** [comment]
Alpha: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/693/cldsv/
Beta: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1447/cldsv/
Stable: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1448/cldsv/
LTS: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1449/cldsv/

**Comment by sayanchowdhury** [comment]
Flatcar website PR: https://github.com/flatcar/flatcar-website/pull/259

**Comment by sayanchowdhury** [comment]
Marking the release as complete.
